# Build Configuration for Travis CI
# https://travis-ci.org

dist: trusty
sudo: required
language: cpp

before_install:
  - echo "Before install"

script:
  - mkdir build64 
  - cd build64
  - cmake ..
  - make
